{"uid":"c0e4793d06605294","name":"test_moving_file","fullName":"tests.moving_file.test_moving_file#test_moving_file","historyId":"94cdfd525afde00f4f1f45b3ebbdf13f","time":{"start":1683312822114,"stop":1683312822114,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'","statusTrace":"@pytest.fixture()\n    def get_file_id():\n        file_path = os.path.join(os.getcwd(), Links.FILE_PATH)\n        headers = {\"Authorization\": f\"Bearer {Links.ACCESS_TOKEN}\"}\n        params = {\"name\": Links.FILE_NAME, \"parents\": [Links.PARENTS]}\n        files = {\"data\": (\"metadata\", json.dumps(params),\n                          \"application/json; charset=UTF-8\"),\n>                \"file\": open(file_path, \"rb\")}\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'\n\nconftest.py:39: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1683312814740,"stop":1683312814740,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"pytestconfig","time":{"start":1683312814740,"stop":1683312814740,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"base_url","time":{"start":1683312814740,"stop":1683312814740,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"delete_output_dir","time":{"start":1683312814740,"stop":1683312814741,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"update_refresh_token","time":{"start":1683312822115,"stop":1683312822243,"duration":128},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"get_file_id","time":{"start":1683312822243,"stop":1683312822244,"duration":1},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/py-pytest/py-pytest/conftest.py\", line 39, in get_file_id\n    \"file\": open(file_path, \"rb\")}\n            ^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'","statusTrace":"@pytest.fixture()\n    def get_file_id():\n        file_path = os.path.join(os.getcwd(), Links.FILE_PATH)\n        headers = {\"Authorization\": f\"Bearer {Links.ACCESS_TOKEN}\"}\n        params = {\"name\": Links.FILE_NAME, \"parents\": [Links.PARENTS]}\n        files = {\"data\": (\"metadata\", json.dumps(params),\n                          \"application/json; charset=UTF-8\"),\n>                \"file\": open(file_path, \"rb\")}\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'\n\nconftest.py:39: FileNotFoundError","steps":[],"attachments":[{"uid":"9d4ab658878981fa","name":"log","source":"9d4ab658878981fa.txt","type":"text/plain","size":151},{"uid":"c5c02b0b436f6d42","name":"stderr","source":"c5c02b0b436f6d42.txt","type":"text/plain","size":120}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"Проверка функции перемещения файла"},{"name":"feature","value":"Проверка перемещения файла"},{"name":"tag","value":"positive"},{"name":"parentSuite","value":"tests.moving_file"},{"name":"suite","value":"test_moving_file"},{"name":"host","value":"fv-az407-736"},{"name":"thread","value":"2314-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.moving_file.test_moving_file"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":4,"unknown":0,"total":6},"items":[{"uid":"a936519c8ae2723f","reportUrl":"https://llizzzzzzzzii.github.io/py-pytest/48//#testresult/a936519c8ae2723f","status":"passed","time":{"start":1683310065732,"stop":1683310067531,"duration":1799}},{"uid":"fa9da798593aece1","reportUrl":"https://llizzzzzzzzii.github.io/py-pytest/47//#testresult/fa9da798593aece1","status":"passed","time":{"start":1683300843215,"stop":1683300845216,"duration":2001}},{"uid":"a175ed61f07ddb4b","reportUrl":"https://llizzzzzzzzii.github.io/py-pytest/46//#testresult/a175ed61f07ddb4b","status":"passed","time":{"start":1683300809424,"stop":1683300811214,"duration":1790}},{"uid":"3a4d2b624a842be6","reportUrl":"https://llizzzzzzzzii.github.io/py-pytest/45//#testresult/3a4d2b624a842be6","status":"broken","statusDetails":"AttributeError: type object 'Links' has no attribute 'FOLDER_FOR_MOVING'","time":{"start":1683299804831,"stop":1683299805128,"duration":297}},{"uid":"f94e94dc5dddc22f","reportUrl":"https://llizzzzzzzzii.github.io/py-pytest/44//#testresult/f94e94dc5dddc22f","status":"passed","time":{"start":1683278986579,"stop":1683278988768,"duration":2189}}]},"tags":["positive"]},"source":"c0e4793d06605294.json","parameterValues":[]}