{"uid":"c6c9b3e1ad9e638d","name":"test_delete_file_to_trash","fullName":"tests.delete_to_trash.test_delete_to_the_trash#test_delete_file_to_trash","historyId":"ddc7c62c35a654c066c51d71e43bec8b","time":{"start":1683312817553,"stop":1683312817553,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'","statusTrace":"@pytest.fixture()\n    def get_file_id():\n        file_path = os.path.join(os.getcwd(), Links.FILE_PATH)\n        headers = {\"Authorization\": f\"Bearer {Links.ACCESS_TOKEN}\"}\n        params = {\"name\": Links.FILE_NAME, \"parents\": [Links.PARENTS]}\n        files = {\"data\": (\"metadata\", json.dumps(params),\n                          \"application/json; charset=UTF-8\"),\n>                \"file\": open(file_path, \"rb\")}\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'\n\nconftest.py:39: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1683312814740,"stop":1683312814740,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"pytestconfig","time":{"start":1683312814740,"stop":1683312814740,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"base_url","time":{"start":1683312814740,"stop":1683312814740,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"delete_output_dir","time":{"start":1683312814740,"stop":1683312814741,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"update_refresh_token","time":{"start":1683312817554,"stop":1683312817713,"duration":159},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"get_file_id","time":{"start":1683312817714,"stop":1683312817714,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/py-pytest/py-pytest/conftest.py\", line 39, in get_file_id\n    \"file\": open(file_path, \"rb\")}\n            ^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'","statusTrace":"@pytest.fixture()\n    def get_file_id():\n        file_path = os.path.join(os.getcwd(), Links.FILE_PATH)\n        headers = {\"Authorization\": f\"Bearer {Links.ACCESS_TOKEN}\"}\n        params = {\"name\": Links.FILE_NAME, \"parents\": [Links.PARENTS]}\n        files = {\"data\": (\"metadata\", json.dumps(params),\n                          \"application/json; charset=UTF-8\"),\n>                \"file\": open(file_path, \"rb\")}\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/py-pytest/data/input.txt'\n\nconftest.py:39: FileNotFoundError","steps":[],"attachments":[{"uid":"2d8ce7270991f81b","name":"log","source":"2d8ce7270991f81b.txt","type":"text/plain","size":151},{"uid":"9e375c3842a24f19","name":"stderr","source":"9e375c3842a24f19.txt","type":"text/plain","size":120}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"Проверка функции удаления файла 'input.txt' в корзину"},{"name":"feature","value":"Проверка удаления файла в корзину"},{"name":"tag","value":"positive"},{"name":"parentSuite","value":"tests.delete_to_trash"},{"name":"suite","value":"test_delete_to_the_trash"},{"name":"host","value":"fv-az407-736"},{"name":"thread","value":"2314-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.delete_to_trash.test_delete_to_the_trash"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"60de2beb1798ef98","reportUrl":"https://llizzzzzzzzii.github.io/py-pytest/48//#testresult/60de2beb1798ef98","status":"passed","time":{"start":1683310060289,"stop":1683310061115,"duration":826}},{"uid":"50c8f93760827583","reportUrl":"https://llizzzzzzzzii.github.io/py-pytest/47//#testresult/50c8f93760827583","status":"passed","time":{"start":1683300833690,"stop":1683300835809,"duration":2119}}]},"tags":["positive"]},"source":"c6c9b3e1ad9e638d.json","parameterValues":[]}